PAD_TOKEN = '#PAD_TOKEN'
PERSON_TYPE = 0
USER_TYPE = 1
SONG_TYPE = 2
PAD_TYPE = 3

SONG_PERSON_REL = 0
PERSON_SONG_REL = 1
USER_SONG_REL = 2
SONG_USER_REL = 3
UNK_REL = 4
END_REL = 5
PAD_REL = 6

ENTITY_EMB_DIM = 64 #64 in paper
TYPE_EMB_DIM =32 #32 in paper
REL_EMB_DIM = 32 #32 in paper
HIDDEN_DIM = 256 #256 in paper
TARGET_SIZE = 2 #since 0 or 1
